@startuml
'https://plantuml.com/class-diagram

class TrackingInventory
{
    + main()
    + start()
}

class TrackingInventoryController
{
    - searchTextArea: TextField
    + InventoryTable: TableView
    + ValCol: TableColumn
    + SerialNumCol: TableColumn
    + NameCol: TableColumn

    + addIInventoryClck()
    + openSaveFileController()
}

class SaveFileAsController
{
    - saveAsChoiceBox: ChoiceBox
    - filePathTextField: TextField

    + saveFormatClick()
    + saveAsClick()
    + loadFileClick()
}

class InputNewItemController
{
    - PriceTextField: TextField
    - SerialNumberTextField: TextField
    - NameTextField: TextField

    + AddItemClick()
}

class DuplicateSerialNumberErrorController
{
    + DupClickClose()
}

class NameLengthErrorController
{
    + LengthClickClose()
}

class SerialFromatErrorController
{
    + LengthClickClose()
}

class createInventory
{
    +getters()
    +setter()
    +putters()
}

javafx.Application <|-- TrackingInventory

TrackingInventory - TrackingInventoryController
TrackingInventoryController - createInventory
TrackingInventoryController -- SaveFileAsController
TrackingInventoryController -- InputNewItemController
TrackingInventoryController -- DuplicateSerialNumberErrorController
InputNewItemController -- DuplicateSerialNumberErrorController
InputNewItemController -- NameLengthErrorController
InputNewItemController -- SerialFromatErrorController

@enduml